# Generated by Django 6.0.5 on 2026-06-01 23:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0002_tournamentrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('type', models.CharField(choices=[('join_request', 'Solicitud de Ingreso'), ('request_accepted', 'Solicitud Aceptada'), ('request_rejected', 'Solicitud Rechazada'), ('tournament_update', 'Actualización de Torneo')], default='tournament_update', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('tournamentId', models.IntegerField(blank=True, null=True)),
                ('requestId', models.IntegerField(blank=True, null=True)),
                ('createdAt', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
