# Generated by Django 6.0.5 on 2026-06-02 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0003_notification'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notification',
        ),
    ]
