# Generated by Django 6.0.5 on 2026-06-02 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0004_delete_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='captain',
        ),
        migrations.RemoveField(
            model_name='tournamentrequest',
            name='captain_name',
        ),
    ]
