# Generated by Django 6.0.5 on 2026-06-02 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('torneos', '0005_remove_team_captain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamentrequest',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
